run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gocritic
    - goimports
    - nilnil
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: true

  nolintlint:
    require-specific: true
