version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocritic
    - nilnil
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true

    nolintlint:
      require-specific: true

    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-QF1008"]

formatters:
  enable:
    - goimports
