name: Create Tag
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get tags
        run: git fetch --tags origin

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Create Tag
        run: |
          set -e -o pipefail
          git tag $(go run scripts/incrementtag/main.go)
          git push --tags

