name: Run Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database:
          - name: mysql
            needs_docker: true
          - name: sqlite
            neeed_docker: false

    name: Integration Tests (${{ matrix.database.name }})

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Stand up DB container
        if: ${{ matrix.database.needs_docker }}
        run: docker compose up -d ${{ matrix.database.name }}

      - name: Run Tests
        run: go test -v ./...
        env:
          TEST_DATABASE: ${{ matrix.database.name }}
