name: Run Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database:
          - name: mysql
          - name: sqlite

    name: Integration Tests (${{ matrix.database.name }})

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Run Tests
        run: go test -v ./...
        env:
          TEST_DATABASE: ${{ matrix.database.name }}
